# Generated by Django 5.2.1 on 2025-05-20 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hazard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('risk_description', models.TextField(verbose_name='风险描述')),
                ('regulations', models.JSONField(blank=True, default=list, verbose_name='相关法规')),
                ('uploader', models.CharField(max_length=100, verbose_name='上传人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='hazard_files/%Y/%m/%d/', verbose_name='附件')),
                ('hazard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='hazard_control.hazard')),
            ],
        ),
    ]
