# Generated by Django 5.2.1 on 2025-05-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hazard_control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hazard',
            name='tatus',
            field=models.CharField(choices=[('待处理', '待处理'), ('整改中', '整改中'), ('已完成', '已完成')], default='待处理', max_length=10, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='hazard',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
