# Generated by Django 5.2.1 on 2025-05-20 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hazard_control', '0002_hazard_tatus_hazard_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hazard',
            old_name='tatus',
            new_name='status',
        ),
    ]
